1. Create a 5 × 5 NumPy matrix containing numbers from 1 to 25 and
print:
○ The first row
○ The last column
○ The diagonal elements


In [11]:
import numpy as np

matrix = np.arange(1, 26).reshape(5, 5)

print("Matrix:")
print(matrix)

print("\nFirst Row:")
print(matrix[0])

print("\nLast Column:")
print(matrix[:, -1])

print("\nDiagonal Elements:")
print(np.diag(matrix))

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

First Row:
[1 2 3 4 5]

Last Column:
[ 5 10 15 20 25]

Diagonal Elements:
[ 1  7 13 19 25]


2. Create two 3 × 3 matrices and perform matrix addition, subtraction,
and matrix multiplication.

In [12]:
print("\n" + "=" * 50)
print("3x3 Matrix Operations")
print("=" * 50)

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition (A + B):\n", A + B)
print("Subtraction (A - B):\n", A - B)
print("Matrix Multiplication (A * B):\n", A * B)


3x3 Matrix Operations
Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition (A + B):
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction (A - B):
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Matrix Multiplication (A * B):
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


3. Create a NumPy array of numbers from 1 to 100 and print all numbers
divisible by 3 using Boolean indexing.


In [13]:
import numpy as np

arr = np.arange(1, 101)

divisible_by_3 = arr[arr % 3 == 0]

print("Numbers divisible by 3:")
print(divisible_by_3)

Numbers divisible by 3:
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


4. Create a 4 × 4 matrix and replace all even numbers with 0.


In [14]:
import numpy as np

matrix = np.arange(1, 17).reshape(4, 4)

print("Original Matrix:")
print(matrix)

matrix[matrix % 2 == 0] = 0

print("\nModified Matrix:")
print(matrix)

Original Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Modified Matrix:
[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


5. Create a 5 × 5 matrix of random integers and find:
○ Maximum value
○ Minimum value
○ Mean
○ Median


In [15]:
import numpy as np

matrix = np.random.randint(1, 101, size=(5, 5))

print("Matrix:")
print(matrix)

print("\nMaximum Value:", np.max(matrix))

print("Minimum Value:", np.min(matrix))

print("Mean:", np.mean(matrix))

print("Median:", np.median(matrix))

Matrix:
[[56 70 41 50 52]
 [64 32 16 69 93]
 [11 15 33 44 33]
 [11  5 12 29 17]
 [98 65 87 79 84]]

Maximum Value: 98
Minimum Value: 5
Mean: 46.64
Median: 44.0


6. Create a NumPy array containing 20 random numbers and sort it in
ascending and descending order

In [16]:
import numpy as np

arr = np.random.randint(1, 101, 20)

print("Original Array:")
print(arr)

ascending = np.sort(arr)
print("\nAscending Order:")
print(ascending)

descending = np.sort(arr)[::-1]
print("\nDescending Order:")
print(descending)

Original Array:
[ 58  88  15  84  30  21  55  40  96  95  27  93  78  99  95  15  93  82
 100  82]

Ascending Order:
[ 15  15  21  27  30  40  55  58  78  82  82  84  88  93  93  95  95  96
  99 100]

Descending Order:
[100  99  96  95  95  93  93  88  84  82  82  78  58  55  40  30  27  21
  15  15]


7. Create a 6 × 6 matrix and print:
○ Main diagonal
○ Upper triangular part
○ Lower triangular part


In [17]:
import numpy as np

matrix = np.arange(1, 37).reshape(6, 6)

print("Original Matrix:")
print(matrix)

print("\nMain Diagonal:")
print(np.diag(matrix))

print("\nUpper Triangular Part:")
print(np.triu(matrix))

print("\nLower Triangular Part:")
print(np.tril(matrix))

Original Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Main Diagonal:
[ 1  8 15 22 29 36]

Upper Triangular Part:
[[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]

Lower Triangular Part:
[[ 1  0  0  0  0  0]
 [ 7  8  0  0  0  0]
 [13 14 15  0  0  0]
 [19 20 21 22  0  0]
 [25 26 27 28 29  0]
 [31 32 33 34 35 36]]


8. Create a NumPy array of 20 elements and reshape it into:
○ 4 × 5 matrix
○ 2 × 10 matrix
○ 5 × 4 matrix


In [18]:
import numpy as np

arr = np.arange(1, 21)

print("Original Array:")
print(arr)

print("\n4 × 5 Matrix:")
print(arr.reshape(4, 5))

print("\n2 × 10 Matrix:")
print(arr.reshape(2, 10))

print("\n5 × 4 Matrix:")
print(arr.reshape(5, 4))

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

4 × 5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

2 × 10 Matrix:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

5 × 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


9. Create a 5 × 5 matrix and calculate the sum of:
○ Each row
○ Each column


In [19]:
import numpy as np

matrix = np.arange(1, 26).reshape(5, 5)

print("Matrix:")
print(matrix)

row_sum = np.sum(matrix, axis=1)
print("\nSum of Each Row:")
print(row_sum)

col_sum = np.sum(matrix, axis=0)
print("\nSum of Each Column:")
print(col_sum)

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Sum of Each Row:
[ 15  40  65  90 115]

Sum of Each Column:
[55 60 65 70 75]


10. Create two arrays and find all common elements between them.

In [20]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr2 = np.array([4, 5, 6, 7, 8, 9, 10])

common = np.intersect1d(arr1, arr2)

print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nCommon Elements:")
print(common)

Array 1:
[1 2 3 4 5 6 7]

Array 2:
[ 4  5  6  7  8  9 10]

Common Elements:
[4 5 6 7]
